project:
  type: website
  output-dir: docs

website:
  title: "Markus Schanta"
  navbar:
    background: light
    right:
      - about.qmd
      - icon: github
        href: https://github.com/markusschanta
      - icon: twitter
        href: https://twitter.com/markusschanta
      - icon: linkedin
        href: https://www.linkedin.com/in/markusschanta/
  page-footer:
    center:
      - text: "Legal"
        href: legal.qmd
      - text: "Privacy"
        href: privacy.qmd
    background: light
  google-analytics:
    tracking-id: "G-YDBEHTJR49"
format:
  html:
    theme: cosmo
    css: styles.css



