project:
  type: website
  output-dir: docs

website:
  title: "Markus Schanta"
  navbar:
    background: light
    right:
      - about.qmd
      - icon: github
        href: https://github.com/markusschanta
      - icon: twitter
        href: https://twitter.com/markusschanta
format:
  html:
    theme: cosmo
    css: styles.css



