---
title: "Legal Information / Impressum"
---

<b>Informationen und Offenlegung gemäß §5 (1) ECG, § 25 MedienG, § 63 GewO und § 14 UGB</b>

<dl>
  <dt>Webseitenbetreiber</dt>
  <dd>Markus Schanta</dd>
  <dt>Kontaktdaten</dt>
  <dd>[@markusschanta](https://twitter.com/markusschanta)</dd>
  <dt>Anwendbare Rechtsvorschrift</dt>
  <dd>[www.ris.bka.gv.at](http://www.ris.bka.gv.at)</dd>
  <dt>Online Streitbeilegung</dt>
  <dd>Verbraucher, welche in Österreich oder in einem sonstigen Vertragsstaat der ODR-VO niedergelassen sind, haben die Möglichkeit Probleme bezüglich dem entgeltlichen Kauf von Waren oder Dienstleistungen im Rahmen einer Online-Streitbeilegung (nach OS, AStG) zu lösen. Die Europäische Kommission stellt eine Plattform hierfür bereit: [https://ec.europa.eu/consumers/odr](https://ec.europa.eu/consumers/odr)</dd>
  <dt>Urheberrecht</dt>
  <dd>Die Inhalte dieser Webseite unterliegen, soweit dies rechtlich möglich ist, diversen Schutzrechten (z.B dem Urheberrecht). Jegliche Verwendung/Verbreitung von bereitgestelltem Material, welche urheberrechtlich untersagt ist, bedarf schriftlicher Zustimmung des Webseitenbetreibers.</dd>
  <dt>Haftungsausschluss</dt>
  <dd>Trotz sorgfältiger inhaltlicher Kontrolle übernimmt der Webseitenbetreiber dieser Webseite keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich. Sollten Sie dennoch auf ausgehende Links aufmerksam werden, welche auf eine Webseite mit rechtswidriger Tätigkeit/Information verweisen, ersuchen wir um dementsprechenden Hinweis, um diese nach § 17 Abs. 2 ECG umgehend zu entfernen. Die Urheberrechte Dritter werden vom Betreiber dieser Webseite mit größter Sorgfalt beachtet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden derartiger Rechtsverletzungen werden wir den betroffenen Inhalt umgehend entfernen.</dd>
</dl>
