---
title: "Privacy Information / Datenschutzerklärung"
---

In folgender Datenschutzerklärung informieren wir Sie über die wichtigsten Aspekte der Datenverarbeitung im Rahmen unserer Webseite. Wir erheben und verarbeiten personenbezogene Daten nur auf Grundlage der gesetzlichen Bestimmungen (Datenschutzgrundverordnung, Telekommunikationsgesetz 2003).

Sobald Sie als Benutzer auf unsere Webseite zugreifen oder diese besuchen wird Ihre IP-Adresse, Beginn sowie Beginn und Ende der Sitzung erfasst. Dies ist technisch bedingt und stellt somit ein berechtigtes Interesse iSv Art 6 Abs 1 lit f DSGVO.

Kontakt mit uns
Wenn Sie uns, entweder über unser Kontaktformular auf unserer Webseite, oder per Email kontaktieren, dann werden die von Ihnen an uns übermittelten Daten zwecks Bearbeitung Ihrer Anfrage oder für den Fall von weiteren Anschlussfragen für sechs Monate bei uns gespeichert. Es erfolgt, ohne Ihre Einwilligung, keine Weitergabe Ihrer übermittelten Daten.

<b>Cookies</b>

Unsere Website verwendet so genannte Cookies. Dabei handelt es sich um kleine Textdateien, die mit Hilfe des Browsers auf Ihrem Endgerät abgelegt werden. Sie richten keinen Schaden an. Wir nutzen Cookies dazu, unser Angebot nutzerfreundlich zu gestalten. Einige Cookies bleiben auf Ihrem Endgerät gespeichert, bis Sie diese löschen. Sie ermöglichen es uns, Ihren Browser beim nächsten Besuch wiederzuerkennen. Wenn Sie dies nicht wünschen, so können Sie Ihren Browser so einrichten, dass er Sie über das Setzen von Cookies informiert und Sie dies nur im Einzelfall erlauben. Bei der Deaktivierung von Cookies kann die Funktionalität unserer Website eingeschränkt sein.

Google Fonts
Unsere Website verwendet Schriftarten von „Google Fonts“. Der Dienstanbieter dieser Funktion ist:

    Google Ireland Limited
    Gordon House, Barrow Street
    Dublin 4
    Ireland
    Tel: +353 1 543 1000

Beim Aufrufen dieser Webseite lädt Ihr Browser Schriftarten und speichert diese in den Cache. Da Sie, als Besucher der Webseite, Daten des Dienstanbieters empfangen kann Google unter Umständen Cookies auf Ihrem Rechner setzen oder analysieren.

Die Nutzung von „Google-Fonts“ dient der Optimierung unserer Dienstleistung und der einheitlichen Darstellung von Inhalten. Dies stellt ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 lit. f DSGVO dar.

Weitere Informationen zu Google Fonts erhalten Sie unter folgendem Link: https://developers.google.com/fonts/faq

Weitere Informationen über den Umgang mit Nutzerdaten von Google können Sie der Datenschutzerklärung entnehmen: https://policies.google.com/privacy?hl=de

Google verarbeitet die Daten auch in den USA, hat sich jedoch dem EU-US Privacy-Shield unterworfen: https://www.privacyshield.gov/EU-US-Framework

<b>Server-Log Files</b>

Diese Webseite und der damit verbundene Provider erhebt im Zuge der Webseitennutzung automatisch Informationen im Rahmen sogenannter „Server-Log Files“. Dies betrifft insbesondere:

<ul>
  <li>IP-Adresse oder Hostname</li>
  <li>den verwendeten Browser</li>
  <li>Aufenthaltsdauer auf der Webseite sowie Datum und Uhrzeit</li>
  <li>aufgerufene Seiten der Webseite</li>
  <li>Spracheinstellungen und Betriebssystem</li>
  <li>Leaving-Page</li>
  <li>ISP (Internet Service Provider)</li>
</ul>

Diese erhobenen Informationen werden nicht personenbezogen verarbeitet oder mit personenbezogenen Daten in Verbindung gebracht.

Der Webseitenbetreiber behält es sich vor, im Falle von Bekanntwerden rechtswidriger Tätigkeiten, diese Daten auszuwerten oder zu überprüfen.

<b>Newsletter</b>

Sie haben die Möglichkeit, über unsere Website unseren Newsletter zu abonnieren. Hierfür benötigen wir Ihre E-Mail-Adresse und ihre Erklärung, dass Sie mit dem Bezug des Newsletters einverstanden sind.

Wenn Sie die Möglichkeit nutzen unseren Newsletter zu abonnieren, wird Ihre Email-Adresse und Ihre Zustimmung/Einverständniserklärung über den Bezug des Newsletters benötigt. In Folge auf die Anmeldung zu unserem Newsletter, erhalten Sie von uns ein Bestätigungs-Email mit einem Link zur Anmeldebestätigung. Eine Stornierung des Abos ist jederzeit möglich.

Ihre Daten im Zusammenhang mit dem Newsletter-Versand werden im Falle einer Stornierung umgehend von uns gelöscht. Die Rechtmäßigkeit der erfolgten Datenverarbeitung bis zum Widerruf, welche aufgrund der Zustimmung passiert ist, wird nicht berührt.

<b>Ihre Rechte als Betroffener</b>

Sie als Betroffener haben bezüglich Ihrer Daten, welche bei uns gespeichert sind grundsätzlich ein Recht auf:

<ul>
  <li>Auskunft</li>
  <li>Löschung der Daten</li>
  <li>Berichtigung der Daten</li>
  <li>Übertragbarkeit der Daten</li>
  <li>Wiederruf und Widerspruch zur Datenverarbeitung</li>
  <li>Einschränkung</li>
</ul>

Wenn sie vermuten, dass im Zuge der Verarbeitung Ihrer Daten Verstöße gegen das Datenschutzrecht passiert sind, so haben Sie die Möglichkeit sich bei uns oder der Datenschutzbehörde zu beschweren.
